recipes-qt/swaplogger/swaplogger.bb

Swaplogger depends on EGL/egl.h which includes EGL/eglplatform.h which in turn includes X11/Xlib.h and X11/Xutil.h unless MESA_EGL_NO_X11_HEADERS is set. When building an image without x11 support we obviously don't want this to happen since those headers won't exist in the sysroot.
Sample fail message:
```
| x86_64-bistro-linux-gcc  -m64 -march=corei7 -mtune=corei7 -mfpmath=sse -msse4.2 --sysroot=/home/zarniwoop/XYZ/build/tmp/sysroots/XYZ  -O2 -pipe -g -feliminate-unused-debug-types -DLINUX=1 -DEGL_API_FB=1 -shared -fPIC -DUSE_EGL   -c -o swaplogger_egl.o swaplogger_egl.c
| In file included from /home/zarniwoop/XYZ/build/tmp/sysroots/XYZ/usr/include/EGL/egl.h:36:0,
|                  from swaplogger_egl.c:26:
| /home/zarniwoop/XYZ/build/tmp/sysroots/XYZ/usr/include/EGL/eglplatform.h:118:2 …
```

swaplogger.bb: omit x11 inclusion if x11 not in DISTRO_FEATURES

---

recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

Bluetooth support should be added in the project specific layer if
there is a need for it. Compilation errors might occur otherwise.

pulseaudio: remove bluetooth and bluez5 from package config

---

recipes-core/images/core-image-bistro-sdk-1.1.bb

Removes the last dependency on ipforward.

core-image-bistro-sdk.bb: Remove dependency on ipforward

---

layers/qt5-layer/recipes-devtools/colortest/colortest_1.0.bb

colortest is a small Qt test program to show a RGB test image
on a screen. It is often needed to test the screen.

Include colortest recipe

---

recipes-core/systemd/systemd_%.bbappend
recipes-core/systemd/systemd_225.bbappend

networkd and resolved should be enabled regardless of systemd version,
so put this in a bbappend matching all system versions

systemd bbappend: Split into version specific and generic part

---

layers/ivi/recipes-core/common-api/common-api-c++-dbus-codegen.bb
layers/ivi/recipes-core/common-api/common-api-c++-dbus_%.bbappend
layers/ivi/recipes-core/common-api/common-api-cmdline.bb
layers/ivi/recipes-core/common-api/common-api-dbus-integration.bb

Applications should only need common-api-c++-dbus as their dependency.

Add native dependencies for CommonAPI code generator.

---

layers/qt5-layer/recipes-qt/qt5/qtwayland-native_git.bbappend

* The component branch and source revision should be stated
in the original meta-qt5 recipe

qtwayland-native_git.bbappend: Remove QtWayland bbappend

---

recipes-support/dbus-proxy/dbus-proxy.bb
recipes-support/ivi-logging/ivi-logging.bb
recipes-support/ivi-logging/ivi-logging.inc

- IVI-logging has been OSS for a long time, but an open recipe for it has been missing.
- The pelagicore fork of dbus-proxy was released to GitHub recently, this adds a recipe for that.

adds recipes for some OSS packages

---

conf/distro/bistro.inc

Not sure why it wasn't done so already (I'm new to all this) but we need
qemu-aarch64 binary for building gobject-introspection, which is required
by many GNOME packages. I noticed this when building Geoclue2.

conf: Generate Qemu binary for AARCH64

---

recipes-core/systemd/systemd-additional-units.bb

Without this we can't be sure the dbus-1 package is available, causing a build issue.

systemd-additional-units: Add dbus dependency

---

layers/multimedia-layer/recipes-multimedia/dleyna/dleyna-git.inc

In newer yocto versions it seems that the ${PN} variable is not
expanded anymore if it is in the SRC_URI, we got the error:
```
ERROR: ExpansionError during parsing
meta-bistro/layers/multimedia-layer/recipes-multimedia/dleyna/dleyna-core_git.bb:
Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)}
which triggered exception FetchError: Fetcher failure: The
SRCREV_FORMAT variable must be set when multiple SCMs are used.
```
Replacing the ${PN} with static strings makes it possible to
use this layer again.

Remove ${PN} from SRC_URI in dleyna

---

layers/multimedia-layer/recipes-multimedia/dleyna/dleyna-git.inc

In newer yocto versions it seems that the ${PN} variable is not
expanded anymore if it is in the SRC_URI, we got the error:
-------------------
ERROR: ExpansionError during parsing
meta-bistro/layers/multimedia-layer/recipes-multimedia/dleyna/dleyna-core_git.bb:
Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)}
which triggered exception FetchError: Fetcher failure: The
SRCREV_FORMAT variable must be set when multiple SCMs are used.
-------------------
Replacing the ${PN} with ${BPN} makes it possible to use this layer again.

Remove ${PN} from SRC_URI

---

recipes-core/dbus-session/dbus-session.bb

A master recipe shouldn't have _append since it's the
one doing the install. Having _append there also would prevent
a downstream bbappend.

Removed append since this is the original recipe.

---

recipes-core/images/core-image-bistro.bb

This adds the packagegroup "packagegroup-tools-bluetooth" to all Bistro
images which satisfy the following:
- Machine type supports the "bluetooth" MACHINE_FEATURE
- "bluetooth" has not been explicitly disabled by removing it from the
default DISTRO_FEATURES set by Bistro.
This means that BT-capable machines will now gain the following
packages:
- bluez5-noinst-tools
- bluez5-obex
- bluez5-testtools
- libasound-module-bluez
If the pulseaudio distro feature has not been removed from the default
DISTRO_FEATURES, the following packages are also installed:
- pulseaudio-module-bluetooth-discover
- pulseaudio-module-bluetooth-policy
- pulseaudio-module-bluez5-discover
- pulseaudio-module-bluez5-device
- pulseaudio-module-switch-on-connect
- pulseaudio-module-loopback
All in all, these packages …

core-image-bistro: Add bluetooth default packages

---

recipes-multimedia/gst-instruments/gst-instruments_git.bb

Add recipe for gst-instruments. This is a set of utilities used to
profile CPU usage of GStreamer pipeline elements. The gst-top utility is
used to launch a gstreamer pipeline and record its profile, and the
gst-report utility is used to analyze reports gathered by gst-top.
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>

gst-instruments: Add recipe

---

layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend

The qtbase OpenSSL PACKAGECONFIG argument is added by default in meta-qt5.

qtbase: remove explicit openssl PACKAGECONFIG

---

README.md

Gordan Markus replaces Igor Socec as the lead maintainer.
Signed-off-by: Igor Socec <igor.socec@pelagicore.com>

Changing maintainers.

---

recipes-support/ivi-logging/ivi-logging.bb

Update SRCREV in order to get fix for ivi-logging on 32-bit systems.

ivi-logging: update SRCREV to latest

---

recipes-devtools/memsnoop/memsnoop.bb
recipes-devtools/memsnoop/memsnoop/memsnoop.c

This utility is used to read and write physical memory addresses using
the /dev/mem kernel interface.
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>
Are we OK w/ inlining small C codes like this? I don't see this utility having a life outside of meta-bistro, but I can of course split it into a git repo with a makefile, etc. if that is preferred.
I would also welcome a code review of the C code.

memsnoop: Add recipe and source file

---

recipes-support/lms/lms_0.4.5.bb

Fix repository link, package missing .la files and add missing RDEPENDS.
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

lms: Fix LightMediaScanner recipe

---

layers/qt5-layer/recipes-qt/swaplogger/swaplogger.bb
recipes-core/systemd/systemd-additional-units.bb
recipes-support/lms/lms_0.4.5.bb

The default fetcher protocol should be https. Often inside of corporate
networks the git port 9418 is blocked. To make it easier for
meta-bistro to get adopted by others we should not use the git
protocol.
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

Change fetcher protocol from git to https

---

recipes-connectivity/blueconnect/blueconnect_git.bb

Add bitbake recipe for blueconnect which is a library for creating
bluetooth demos.
Signed-off-by: Viktor Sjölind <viktor.sjolind@pelagicore.com>

Add recipe for blueconnect

---

classes/testmedia.bbclass
recipes-multimedia/test-multimedia/gstreamer-testmedia.bb

This adds a recipe and bbclass for deploying test media. Media is
extracted from a tarball specified by SRC_URI, and known media types are
extracted and grouped in to packages, installed in /usr/share.
Audio filed can be installed by including test-multimedia-audio, video
files are in test-multimedia-video, etc.

Add recipe and helper class for deploying media

---

recipes-temporary-patches/cairo/cairo_%.bbappend

In some cases there are more files created than the .la file which also
needs to be removed.
Signed-off-by: Viktor Sjölind <viktor.sjolind@pelagicore.com>

cairo: Remove all libtrace files

---

recipes-core/systemd/systemd-genivi-targets/focussed.target

Currently focussed.target starts after node-state-controller, but
the service is actually called node-startup-controller.
Signed-off-by: Erik Botö <erik.boto@pelagicore.com>

systemd-genivi-targets: Fix focussed.target

---

recipes-core/packagegroups/packagegroup-bistro-utils.bb

Split packagegroup utils into two groups:
One group for general utils
One group for debug utils
Signed-off-by: Therese Nordqvist <therese.nordqvist@pelagicore.com>

packagegroups: Split into debug utils and utils

---

scripts/Jenkinsfile

Currently, every pull request and branch build is built against master
branch of the pelux-manifests, which is incorrect since both meta layers
and pelux-manifests follow the Yocto branching strategy, making some of
the branches incompatible between each other.
Build the layer against the corresponding branch of the PELUX manifest
instead, e.g. sumo against sumo and master against master.
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>
(cherry picked from commit 65ecd9dd5c360b400a68803ed13957a9ed865568)

Jenkinsfile: build against analogous manifest branch

---

recipes-core/systemd/systemd_%.bbappend

The default value of PACKAGECONFIG in upstream systemd recipe already
contain networkd and resolved.
This bbappend use += to add those values, and the original recipe uses
a weak default value (??=), which means that those weak defaults will
not be used. Instead PACKAGECONFIG will only contain networkd and
resolved which is not the intention.
Signed-off-by: Erik Botö <erik.boto@pelagicore.com>

systemd: remove obsolete bbappend

---

recipes-devtools/gdbus-codegen-glibmm/gdbus-codegen-glibmm.inc
recipes-devtools/gdbus-codegen-glibmm/gdbus-codegen-glibmm_2.99.0.bb

Change to use both a .inc and a .bb file. This enables projects to use
more than one version of the tool.
Signed-off-by: Therese Nordqvist <therese.nordqvist@pelagicore.com>

gdbus-codegen-glibmm: Split recipe into .inc and .bb file

---

recipes-alexa/snowboy/snowboy_1.3.0.bb

Smoke tests were failing to start bitbaking due to non-existing
qemux86-64 machine. This fixes the issue and allows the minimal image to
be bitbaked.
Signed-off-by: Fisnik Hajredini <fhajredini@luxoft.com>

Snowboy: Add qemu as machine

---

recipes-devtools/pcie-debug/files/Makefile
recipes-devtools/pcie-debug/pcie-debug_git.bb

PCI-Debug is a tool that is used to probe pci devices in Linux systems
from userspace.
The recipe is added since the tools is used in some of our demos.
Signed-off-by: Viktor Sjölind <vsjolind@luxoft.com>

Add recipe for pcie-debug
